// ============================================================
// Vanij — Firebase options
//
// Normally this file is generated by `flutterfire configure`. We provide it
// by hand here so the project builds end-to-end without the FlutterFire CLI.
//
// NOTE: The Android values mirror the `google-services.json` committed under
// `android/app/`. The `apiKey` below is the public-facing Firebase Android
// API key — per Firebase docs this value is not a secret and may be
// embedded in the client; true secrets live in Google Cloud Secret Manager
// on the backend.
// ============================================================
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Vanij web is not supported in Sprint 1 — Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'Platform ${defaultTargetPlatform.name} is not configured. '
          'Vanij currently targets Android only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHOWGJcIPXCQ2A4CvjKDQp8RWjcoLaU0',
    appId: '1:756301227951:android:a7a1147def4fedd572f15a',
    messagingSenderId: '756301227951',
    projectId: 'vanij-6cc7e',
    storageBucket: 'vanij-6cc7e.firebasestorage.app',
  );
}
